// Generated by apps/anfis_train/anfis_train.py -- do not edit by hand.
// Mackey-Glass x(t+6) from x(t-18), x(t-12), x(t-6), x(t).
// Generalized-bell membership functions, exponent 1 -- arithmetic
// only, so this model deploys at FLOAT=0 / STD=0.
// train RMSE 0.003180, test RMSE 0.004066 over 500 held-out samples.

#pragma once

#include <cstddef>
#include <cstdint>

namespace anfis_mackey_glass_model {
    constexpr std::size_t NumberOfInputs = 4;
    constexpr std::size_t NumberOfMembershipFunctionsPerInput = 2;
    constexpr std::size_t NumberOfRules = 16;
    constexpr std::size_t NumberOfOutputs = 1;
    constexpr std::size_t NumberOfParametersPerMembershipFunction = 2;

    // Membership function: tinymind::GeneralizedBellMembershipFunction<ValueType, 1>
    // [input][membershipFunction]{a, c}
    constexpr double Premise[16] = {
        0.493456688, 0.419800284, 0.161323155, 1.09181123, 0.339492899, 0.64189672,
        0.347247203, 1.37963766, 0.404111887, 0.563750482, 0.437015419, 1.40865845,
        0.496745133, 0.533538015, 0.104399937, 1.48599289
    };

    // [rule][input] -- antecedent membership function index.
    constexpr uint8_t RuleTable[64] = {
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1
    };

    // [rule][output]{p_0 .. p_{n-1}, q} -- first-order consequent.
    constexpr double Consequent[80] = {
        -0.00342527488, 0.130865186, -0.23611492, 1.35751182, -0.0353504197,
        -17.2894233, 28.6609511, -10.5929161, -5.41419257, 8.79898502,
        1.34697687, 0.921759994, 3.32577524, -2.77387593, -1.6014044,
        -12.390729, -23.0493141, 20.6539522, 6.62996, -8.52439648,
        -3.46763273, 6.59948505, -7.59126131, 1.5690642, 2.47930769,
        129.286332, -168.980564, 156.082799, 25.2759745, -106.720386,
        1.66783, -5.66842102, -2.01109223, 1.93744606, 7.71740238,
        -28.0395501, 29.8486806, -31.2573763, 8.64786324, 12.3672251,
        1.20335518, -1.16309237, 0.382977566, 1.59135432, -0.0961627632,
        -83.347199, 3.49161789, 19.3336962, -20.5147963, 84.9399614,
        -4.01480998, 3.59906705, 0.0300574336, -1.31544018, 3.0268993,
        43.7866796, -9.10892806, -1.5899341, 8.162274, -33.1409184,
        -4.73562153, -0.95969973, 3.85830819, -3.84264027, 5.70538045,
        89.2429092, 29.6510277, -49.3434009, 5.96302497, -88.6004497,
        -0.58098877, 2.00937552, -0.354939873, 2.64694108, -3.60495665,
        -23.0656407, 5.655382, 11.6355343, 9.08290614, -7.9591826
    };
}
