#
# Copyright (c) 2026 Dan McLeran
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

"""Train the Mackey-Glass ANFIS and emit the headers the C++ example builds against.

Jang's original ANFIS benchmark: predict x(t+6) of the Mackey-Glass chaotic
time series from four delayed samples, x(t-18), x(t-12), x(t-6), x(t). Two
membership functions per input over the full grid is 2^4 = 16 rules, which
sits inside the rule budget real fuzzy hardware actually ships.

Also runs the rule-pruning study that motivates cpp/anfis.hpp carrying an
explicit rule table instead of an implicit grid, and writes both results
into generated headers so `make run` reproduces every CSV with no Python
in the loop -- CI never runs this file.

Regenerate with:  make regenerate-model
"""

import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "apps", "anfis_train"))

import anfis_train as at  # noqa: E402

# Jang's benchmark parameters.
TAU = 17
DELAYS = (18, 12, 6, 0)
HORIZON = 6
FIRST_T = 118
N_SAMPLES = 1000
N_TRAIN = 500

N_MFS = 2
EPOCHS = 200
STEP = 0.005

# The rule-pruning study runs on a deliberately oversized 3-MF grid, where
# the curse of dimensionality actually bites.
STUDY_MFS = 3
STUDY_THRESHOLDS = (0.0, 0.001, 0.005, 0.01, 0.02)


def mackey_glass(n, tau=TAU, beta=0.2, gamma=0.1, power=10, x0=1.2):
    """dx/dt = beta*x(t-tau)/(1 + x(t-tau)^power) - gamma*x(t), dt = 1.

    Euler at dt = 1 with tau = 17 is the convention the ANFIS literature
    uses for this benchmark, so the numbers here are comparable to the
    published ones.
    """
    x = [x0] * (tau + 1)
    for _ in range(n + 200):
        xt = x[-1]
        xd = x[-1 - tau]
        x.append(xt + beta * xd / (1.0 + xd ** power) - gamma * xt)
    return np.array(x)


def build_dataset():
    series = mackey_glass(N_SAMPLES + FIRST_T + HORIZON + max(DELAYS))
    idx = np.arange(FIRST_T, FIRST_T + N_SAMPLES)
    X = np.stack([series[idx - d] for d in DELAYS], axis=1)
    y = series[idx + HORIZON]
    return X[:N_TRAIN], y[:N_TRAIN], X[N_TRAIN:], y[N_TRAIN:]


def run_pruning_study(X_tr, y_tr, X_te, y_te):
    """Train an oversized grid, prune at several thresholds, record both errors."""
    rows = []
    for threshold in STUDY_THRESHOLDS:
        model = at.build_grid_anfis(X_tr, STUDY_MFS)
        model.fit(X_tr, y_tr, epochs=EPOCHS, step=STEP)
        kept = model.prune(X_tr, y_tr, threshold)
        rows.append((threshold, len(kept), STUDY_MFS ** X_tr.shape[1],
                     at.rmse(model.predict(X_tr), y_tr),
                     at.rmse(model.predict(X_te), y_te)))
        print("  threshold %.3f -> kept %2d/%d  train RMSE %.6f  test RMSE %.6f"
              % rows[-1])
    return rows


def emit_data_header(path, X_te, y_te, history, study):
    """Dataset + training history + pruning study, as plain C++ arrays.

    Carrying these as data means the C++ example can write every CSV the
    plot needs from one `make run`, with no Python dependency in CI.
    """
    def rows(values, per_line, fmt):
        out = []
        vals = list(values)
        for start in range(0, len(vals), per_line):
            chunk = vals[start:start + per_line]
            out.append("        " + ", ".join(fmt % v for v in chunk))
        return ",\n".join(out)

    n_test, n_inputs = X_te.shape
    parts = [
        "// Generated by examples/anfis_mackey_glass/train.py -- do not edit by hand.\n",
        "// Mackey-Glass held-out test set, hybrid-training history, and the\n",
        "// rule-pruning study, carried as data so the example needs no Python.\n",
        "\n#pragma once\n\n#include <cstddef>\n\n",
        "namespace anfis_mackey_glass_data {\n",
        "    constexpr std::size_t NumberOfTestSamples = %d;\n" % n_test,
        "    constexpr std::size_t NumberOfEpochs = %d;\n" % len(history),
        "    constexpr std::size_t NumberOfPruningRows = %d;\n\n" % len(study),
        "    // [sample][input]\n",
        "    constexpr double TestInputs[%d] = {\n%s\n    };\n\n"
        % (n_test * n_inputs, rows(X_te.reshape(-1), 4, "%.9g")),
        "    constexpr double TestTargets[%d] = {\n%s\n    };\n\n"
        % (n_test, rows(y_te, 6, "%.9g")),
        "    // train RMSE / test RMSE per epoch\n",
        "    constexpr double TrainRmse[%d] = {\n%s\n    };\n\n"
        % (len(history), rows([h[1] for h in history], 6, "%.9g")),
        "    constexpr double TestRmse[%d] = {\n%s\n    };\n\n"
        % (len(history), rows([h[2] for h in history], 6, "%.9g")),
        "    // threshold, rules kept, rules total, train RMSE, test RMSE\n",
        "    constexpr double PruningThreshold[%d] = {\n%s\n    };\n"
        % (len(study), rows([s[0] for s in study], 6, "%.9g")),
        "    constexpr std::size_t PruningRulesKept[%d] = {\n%s\n    };\n"
        % (len(study), rows([s[1] for s in study], 8, "%d")),
        "    constexpr std::size_t PruningRulesTotal[%d] = {\n%s\n    };\n"
        % (len(study), rows([s[2] for s in study], 8, "%d")),
        "    constexpr double PruningTrainRmse[%d] = {\n%s\n    };\n"
        % (len(study), rows([s[3] for s in study], 6, "%.9g")),
        "    constexpr double PruningTestRmse[%d] = {\n%s\n    };\n"
        % (len(study), rows([s[4] for s in study], 6, "%.9g")),
        "}\n",
    ]
    with open(path, "w") as handle:
        handle.write("".join(parts))
    return path


def main():
    X_tr, y_tr, X_te, y_te = build_dataset()
    print("dataset: %d train / %d test, %d inputs, target range [%.3f, %.3f]"
          % (len(y_tr), len(y_te), X_tr.shape[1], y_te.min(), y_te.max()))

    model = at.build_grid_anfis(X_tr, N_MFS)
    print("model: %d rules, %d premise parameters, %d consequent parameters"
          % (model.n_rules, model.premise_flat().size, model.consequent_flat().size))

    model.solve_consequents(X_tr, y_tr)
    lse_only = at.rmse(model.predict(X_te), y_te)
    print("least squares alone: test RMSE %.6f" % lse_only)

    print("hybrid training (%d epochs, step %.4f):" % (EPOCHS, STEP))
    history = model.fit(X_tr, y_tr, epochs=EPOCHS, step=STEP,
                        X_val=X_te, y_val=y_te, verbose=True)

    train_rmse = at.rmse(model.predict(X_tr), y_tr)
    test_rmse = at.rmse(model.predict(X_te), y_te)
    print("final: train RMSE %.6f  test RMSE %.6f  (%.2f%% of target range)"
          % (train_rmse, test_rmse, 100.0 * test_rmse / (y_te.max() - y_te.min())))

    print("rule pruning study on an oversized %d-MF grid:" % STUDY_MFS)
    study = run_pruning_study(X_tr, y_tr, X_te, y_te)

    at.emit_model_header(
        os.path.join(HERE, "anfis_model.hpp"), model,
        namespace="anfis_mackey_glass_model",
        comment=("Mackey-Glass x(t+6) from x(t-18), x(t-12), x(t-6), x(t).\n"
                 "Generalized-bell membership functions, exponent 1 -- arithmetic\n"
                 "only, so this model deploys at FLOAT=0 / STD=0.\n"
                 "train RMSE %.6f, test RMSE %.6f over %d held-out samples."
                 % (train_rmse, test_rmse, len(y_te))))
    emit_data_header(os.path.join(HERE, "anfis_data.hpp"),
                     X_te, y_te, history, study)
    print("wrote anfis_model.hpp and anfis_data.hpp")


if __name__ == "__main__":
    main()
