# Simple Makefile for the activation function LUTs
default :
#	Build the application
	g++ -O3 -Wall -o activationTableGenerator activationTableGenerator.cpp -I../../cpp/ -std=c++17 -lstdc++fs

# Remove all object files
clean:
	rm -f activationTableGenerator
	rm -f *.o
