// Generated by apps/anfis_train/anfis_train.py -- do not edit by hand.
// Ridge-regularized (lambda = 1e-06) so the consequents stay small
// enough for int8. See train.py for why that matters.

#pragma once

#include <cstddef>
#include <cstdint>

namespace anfis_int8_model {
    constexpr std::size_t NumberOfInputs = 4;
    constexpr std::size_t NumberOfMembershipFunctionsPerInput = 2;
    constexpr std::size_t NumberOfRules = 16;
    constexpr std::size_t NumberOfOutputs = 1;
    constexpr std::size_t NumberOfParametersPerMembershipFunction = 2;

    // Membership function: tinymind::GeneralizedBellMembershipFunction<ValueType, 1>
    // [input][membershipFunction]{a, c}
    constexpr double Premise[16] = {
        0.326327475, 0.468804957, 0.122314666, 1.10279945, 0.188894484, 0.503055994,
        0.149486513, 1.18361248, 0.423335426, 0.461871389, 0.15780815, 1.38101699,
        0.389915067, 0.436391146, 0.144727772, 1.31355794
    };

    // [rule][input] -- antecedent membership function index.
    constexpr uint8_t RuleTable[64] = {
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1
    };

    // [rule][output]{p_0 .. p_{n-1}, q} -- first-order consequent.
    constexpr double Consequent[80] = {
        0.330031563, 0.61341665, -0.217002324, 0.963741428, -0.258154563,
        -0.321758674, 1.1073991, 0.159464551, 1.80944198, -1.30322909,
        -0.517819284, -0.519057584, 1.9088646, -0.921063082, 0.225369696,
        -3.38422051, -3.44464959, 6.626479, 1.9967848, -5.05931409,
        -1.01078955, 1.0215897, -1.54823394, 0.361561455, 1.8019938,
        8.32924691, -9.57952671, 7.02862603, -2.58341026, 0.153342135,
        1.13496429, -3.02586967, -1.9792085, 2.20219519, 4.88487456,
        -3.58941955, 1.39781631, -6.28970255, 3.56391289, 5.4098616,
        -0.509307917, -0.146266437, 0.410060208, 0.393651411, 1.15526563,
        -3.70621749, -1.4581889, 0.33241132, -1.88671423, 7.40184846,
        -1.53716562, 0.210175805, 2.94559255, -3.95840532, 3.05160963,
        -0.318018569, -4.52716756, 3.75328795, 0.21903494, 2.58877747,
        -2.34441495, -0.839737958, 1.36302822, -0.802239005, 3.51263834,
        4.72126985, -2.46055911, -0.332945537, 0.884488139, -2.53051045,
        -1.6044515, 0.0466711735, 0.429243929, 1.84550056, 0.0814520973,
        -1.14163158, -0.31169372, 1.13633615, 2.22895069, -1.62101501
    };
}
