#
# Copyright (c) 2026 Dan McLeran
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

"""Fit the ridge-regularized Mackey-Glass ANFIS the int8 exemplar deploys.

Same task and same architecture as examples/anfis_mackey_glass -- Jang's
benchmark, 4 delayed inputs, 2 bells per input, 16 rules -- with one
difference that matters only for int8: the consequents are solved with a
ridge penalty.

An unregularized least-squares solve produces consequent coefficients that
nearly cancel, the largest reaching 169 against an output spanning about 0.94.
In float that is harmless. In int8 it is not: the input carries half a
quantization step of error, and a coefficient of 169 amplifies it well past
the output quantum, breaking the cancellation the fit depends on. The
unregularized model is emitted alongside so the example can show the
difference rather than assert it.

Regenerate with:  make regenerate-model
"""

import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "apps", "anfis_train"))

import anfis_train as at  # noqa: E402

TAU = 17
DELAYS = (18, 12, 6, 0)
HORIZON = 6
FIRST_T = 118
N_SAMPLES = 1000
N_TRAIN = 500

N_MFS = 2
EPOCHS = 200
STEP = 0.005
RIDGE = 1e-6


def mackey_glass(n, tau=TAU, beta=0.2, gamma=0.1, power=10, x0=1.2):
    x = [x0] * (tau + 1)
    for _ in range(n + 200):
        xt = x[-1]
        xd = x[-1 - tau]
        x.append(xt + beta * xd / (1.0 + xd ** power) - gamma * xt)
    return np.array(x)


def build_dataset():
    series = mackey_glass(N_SAMPLES + FIRST_T + HORIZON + max(DELAYS))
    idx = np.arange(FIRST_T, FIRST_T + N_SAMPLES)
    X = np.stack([series[idx - d] for d in DELAYS], axis=1)
    y = series[idx + HORIZON]
    return X[:N_TRAIN], y[:N_TRAIN], X[N_TRAIN:], y[N_TRAIN:]


def emit_data_header(path, X_te, y_te, X_tr):
    """Held-out set plus the calibration ranges the C++ side needs.

    The ranges come from the TRAINING split, never the held-out one --
    calibrating on test data would leak it into the deployed model.
    """
    def rows(values, per_line, fmt):
        out = []
        vals = list(values)
        for start in range(0, len(vals), per_line):
            out.append("        " + ", ".join(fmt % v for v in vals[start:start + per_line]))
        return ",\n".join(out)

    n_test, n_inputs = X_te.shape
    parts = [
        "// Generated by examples/anfis_mackey_glass_int8/train.py -- do not edit by hand.\n",
        "// Mackey-Glass held-out set and training-split calibration ranges.\n",
        "\n#pragma once\n\n#include <cstddef>\n\n",
        "namespace anfis_int8_data {\n",
        "    constexpr std::size_t NumberOfTestSamples = %d;\n" % n_test,
        "    constexpr double InputMin  = %.9g;\n" % X_tr.min(),
        "    constexpr double InputMax  = %.9g;\n" % X_tr.max(),
        "    constexpr double OutputMin = %.9g;\n" % y_te.min(),
        "    constexpr double OutputMax = %.9g;\n\n" % y_te.max(),
        "    constexpr double TestInputs[%d] = {\n%s\n    };\n\n"
        % (n_test * n_inputs, rows(X_te.reshape(-1), 4, "%.9g")),
        "    constexpr double TestTargets[%d] = {\n%s\n    };\n"
        % (n_test, rows(y_te, 6, "%.9g")),
        "}\n",
    ]
    with open(path, "w") as handle:
        handle.write("".join(parts))


def fit(X_tr, y_tr, ridge):
    model = at.build_grid_anfis(X_tr, N_MFS)
    model.fit(X_tr, y_tr, epochs=EPOCHS, step=STEP, ridge=ridge)
    return model


def main():
    X_tr, y_tr, X_te, y_te = build_dataset()

    ridged = fit(X_tr, y_tr, RIDGE)
    plain = fit(X_tr, y_tr, 0.0)

    def peak(model):
        coef = model.theta.reshape(model.n_rules, model.n_inputs + 1,
                                   model.n_outputs)[:, :model.n_inputs, :]
        return float(np.abs(coef).max())

    print("ridge %.0e : test RMSE %.6f   largest consequent coefficient %8.2f"
          % (RIDGE, at.rmse(ridged.predict(X_te), y_te), peak(ridged)))
    print("ridge 0    : test RMSE %.6f   largest consequent coefficient %8.2f"
          % (at.rmse(plain.predict(X_te), y_te), peak(plain)))

    at.emit_model_header(
        os.path.join(HERE, "anfis_int8_model.hpp"), ridged,
        namespace="anfis_int8_model",
        comment=("Ridge-regularized (lambda = %.0e) so the consequents stay small\n"
                 "enough for int8. See train.py for why that matters." % RIDGE))
    at.emit_model_header(
        os.path.join(HERE, "anfis_int8_model_unregularized.hpp"), plain,
        namespace="anfis_int8_model_unregularized",
        comment=("Ordinary least squares, no ridge. Carried ONLY so the example can\n"
                 "show what large cancelling consequents cost in int8."))
    emit_data_header(os.path.join(HERE, "anfis_int8_data.hpp"), X_te, y_te, X_tr)
    print("wrote anfis_int8_model.hpp, anfis_int8_model_unregularized.hpp, anfis_int8_data.hpp")


if __name__ == "__main__":
    main()
